name: Deploy to Production

on:
  push:
    branches:
      - main  # 这里根据你的主分支名称来设置

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          npm run build
          npm run dev
          --host    # 这里根据你的实际部署命令来设置，可能是 npm run deploy 或其他命令

      - name: Deploy to Hosting Provider
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          # 在这里执行部署到主机提供商的命令，比如使用 supabase 提供的 CLI 工具或其他方法
          # 示例：supabase deploy --env production
